# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: f20170971@goa.bits-pilani.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: GangulyRijul
github_username: Rijul1999
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rijul Ganguly"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "I am a SDE-I in the Localshops Team at Amazon BLR. Previously I completed my B.E. in Computer Science and Engineering from Birla Institute of Technology and Science
            Pilani, Goa Campus."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rijul1999.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GangulyRijul"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rijul1999"
    - label: "Resume"
      icon: "fab fa-fw fa-instagram"
      url: "https://github.com/Rijul1999/Rijul1999.github.io/raw/master/Resume.pdf"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GangulyRijul"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rijul1999"
    - label: "Resume"
      icon: "fab fa-fw fa-instagram"
      url: "https://github.com/Rijul1999/Rijul1999.github.io/raw/master/Resume.pdf"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
teach_archive:
  type: liquid
  path: /teach/
